### ISSUE TITLE
I liked your theme

### ISSUE THREAD

**Issue by BelieveInBunny** [DylanGangat/Animestudio#1]
Hi,
I liked your theme, are you available to work? I wanted a theme like zoro.to

Thanks

**Comment by DylanGangat** [comment]
Hey man 👋 . Yes I am able for work but what do  you mean by refering to theme. Can you explain exactly what your you want?

**Comment by BelieveInBunny** [comment]
> Hey man 👋 . Yes I am able for work but what do you mean by refering to theme. Can you explain exactly what your you want?

yes, I am looking for the theme like zoro.to (html, css and js) and integrate it with my backend script.
My friend and I am working on a script and we are having trouble with front end and I saw your theme it is good and I wanted to make one like zoro.to for myself

**Comment by DylanGangat** [comment]
That sounds really cool man but I think the scale of that project is too big for me right now because I'm actually getting ready for applying for jobs so I'm going to have to spend a lot of time on interview questions and stuff. You know how it is. But anyway I hope everything goes well with figuring out the frontend aspect of your project

**Comment by BelieveInBunny** [comment]
> That sounds really cool man but I think the scale of that project is too big for me right now because I'm actually getting ready for applying for jobs so I'm going to have to spend a lot of time on interview questions and stuff. You know how it is. But anyway I hope everything goes well with figuring out the frontend aspect of your project

I understand, if you think you can work on it, let me know
